name: Build

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    uses: ./.github/workflows/build-template.yml
    with:
      node-version: "22"
      app-base-url: ${{ vars.APP_BASE_URL }}
      auth0-domain: ${{ vars.AUTH0_DOMAIN }}
      auth0-callback-url: ${{ vars.AUTH0_CALLBACK_URL }}
      auth0-audience: ${{ vars.AUTH0_AUDIENCE }}
      api-server-url: ${{ vars.NEXT_PUBLIC_API_SERVER_URL }}
    secrets: inherit
